### PR TITLE
Added TextField

### PR DESCRIPTION
**Pull request by ChandanKhamitkar**
1. FilledTextFields
2. OutlinedTextFields

**Preview 👁️👁️**

### Filled
https://github.com/user-attachments/assets/8f0f2f8d-1c2c-49e3-a3b7-6b2e1737aa03

 ### Outlined

https://github.com/user-attachments/assets/179cd967-5cc5-4a80-b4de-ef7c3099f557

### CODE REVIEW

**Comment by ChandanKhamitkar** [comment]
@ManasMalla 
- As you go through the PR, you may get to know that a few of the styles were written in both the `component file `& `global.css file.`
- If any changes need to be made, let me know.

**Comment by ChandanKhamitkar** [comment]
**Updated Text-Fields with a few more functionalities.**

- Fixed Padding issues in the Filled Text Field
- Added Recursive function in Outlined Text Fields when the label moves; it gets the parent's Background Color and sets the  Background color as the label's.
- Trailing Icons only appear when ever input has been given.
- Toggle visibility of password + icon toggle.

https://github.com/user-attachments/assets/4022f17c-cea7-4f53-a5dd-afcb25a7634b

**Comment by ManasMalla** [comment]
@ChandanKhamitkar, that's great progress. It almost looks fine to me. If you can, ensure the hint is centered in the FilledTextField when the user hasn't entered anything. Also, the hint on OutlinedTextField, can you try to bring it to its position towards the left as per the official [docs](https://m3.material.io/components/text-fields/specs#605e24f1-1c1f-4c00-b385-4bf50733a5ef).
image
image
image

**Comment by ChandanKhamitkar** [comment]
Now, the FilledTextField has the correct alignment for the label.

image

**Comment by ManasMalla** [comment]
Wonderful. LGTM.

**Pull request merged**
